additional_parameters: {}                                # Name and value of additional parameter which will be included in every recording test file
additional_arguments:                                    # Name and value of additional arguments which will be included in every recording test file
  goal2d:
    [-0.5, -0.3, 0.0]
